# Configuration for the Blunderbuss GitHub app. For more info see
# https://github.com/googleapis/repo-automation-bots/tree/main/packages/blunderbuss
assign_issues:
  - googleapis/yoshi-java
assign_prs:
  - googleapis/yoshi-java
assign_prs_by:
  - labels:
    - samples
    to:
    - googleapis/java-samples-reviewers
