bumpMinorPreMajor: true
handleGHRelease: true
releaseType: java-yoshi
branches:
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-yoshi
    branch: java7
extraFiles:
  - src/main/java/com/google/cloud/logging/logback/LoggingAppender.java
